export const SAVE_LOGIN_USER_SUCCESS ="SAVE_LOGIN_USER_SUCCESS";
export const SAVE_LOGIN_USER_INITIATE ="SAVE_LOGIN_USER_INITIATE";
export const LOGIN_FAILED = "LOGIN_FAILED";


export const SAVE_SIGNUP_USER_INITIATE ="SAVE_SIGNUP_USER_INITIATE";
export const SAVE_SIGNUP_USER_SUCCESS ="SAVE_SIGNUP_USER_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const GET_TEAMS_DETAILS_INITIATE ='GET_TEAMS_DETAILS_INITIATE';
export const GET_TEAMS_DETAILS_SUCCESS ='GET_TEAMS_DETAILS_SUCCESS';
export const GET_TEAMS_DETAILS_FAIL ='GET_TEAMS_DETAILS_FAIL';